### ISSUE TITLE
Update to Node20 and switch `pkg`

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#111]
### Specification

There are two parts to this issue. 
1. Once again updating to node 20 as it's supported by the packager now.
2. Switch the packager from `vercel/pkg` to https://github.com/yao-pkg/pkg

### Additional context

Related https://github.com/MatrixAI/Polykey-CLI/issues/40#issuecomment-1913946054

### Tasks

1. Update to node 20
2. switch to using `yao-pkg/pkg` for packaging. This includes removing the use of `vercel/pkg`.

**Comment by CMCDragonkai** [comment]
When switching to node 20 and the new yao pkg, enable the arm64 builds. It's now available. See: https://github.com/yao-pkg/pkg-fetch/releases

Will need to update `utils.nix` and `.gitlab-ci.yml` to produce those builds. Also this infrastructure should be moved to `nixpkgs-matrix` so we can use it across multiple projects.

**Comment by CMCDragonkai** [comment]
PK is already on Node 20. This should be part of the #40.

**Comment by CMCDragonkai** [comment]
Node 20 is LTS since october last year.

**Comment by amydevs** [comment]
This seems to have already been done.

> enable the arm64 builds

We will need to make arm64 builds for the dependencies before this can happen (js-db, js-mdns, etc.)

**Comment by CMCDragonkai** [comment]
This is done? Where's the PR.

**Comment by amydevs** [comment]
pretty sure the switch to `yao-pkg` was done in 2ef4aa966fd87b9e2902712da14d0bffa6c79bd8

**Comment by amydevs** [comment]
ah wait, the environment scripts and the flake still refer to node 18, will switch it over

**Comment by amydevs** [comment]
https://github.com/yao-pkg/pkg#targets

It seems that it is not possible to generate arm64 macos binaries on any systems other than an arm64 macos machine.

This is the error when i try running it on my nixos x64 linux laptop:

```bash
pkg dist/polykey.js --config=/build/3x0x90lzbmrynhqyxs0fj5msdqiidd93-source/pkg.json --targets=node20-macos-arm64 --no-bytecode --no-native-build --public --public-packages='*>
> pkg@5.11.4
> Fetching base Node.js binaries to PKG_CACHE_PATH
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v20.11.1-macos-arm64        [] 0%> Not found in remote cache:
  {"tag":"v3.5","name":"node-v20.11.1-macos-arm64"}
> Building base binary from source:
  built-v20.11.1-macos-arm64
> Error! Not able to build for 'macos' here, only for 'linux'
node:internal/errors:865
  const err = new Error(message);
              ^

Error: Command failed: pkg dist/polykey.js --config=/build/3x0x90lzbmrynhqyxs0fj5msdqiidd93-source/pkg.json --targets=node20-macos-arm64 --no-bytecode --no-native-build --publ>
    at checkExecSyncError (node:child_process:890:11)
    at Object.execFileSync (node:child_process:926:15)
    at main (/build/3x0x90lzbmrynhqyxs0fj5msdqiidd93-source/scripts/pkg.js:149:16) {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 950,
  stdout: null,
  stderr: null
}
```
