### ISSUE TITLE
Version Metadata Standardization

### ISSUE THREAD

**Issue by amydevs** [MatrixAI/Polykey-CLI#121]
### Specification
This issue aims to standardize the `versionMetadata` supplied by the `agentStatus` RPC call and labels stored on the generated Docker images.

__This specification applies in the context of official PK-CLI only!__ Third-party Polykey Agent applications may choose to follow this spec, but it is not guaranteed.

The `versionMetadata` under the context of PK-CLI should follow these rules:
- It should be of type `{ [key: string]: string }`.
- The object structure can only have string values.
- The object structure cannot be nested.
- Version data related to PK-CLI itself (`commitHash`, `version`) should not be prefixed.
- Version data related to the PK library it is using should be prefixed with `lib` (`libVersion`, `libCommitHash`, etc).
- Other prefixes maybe decided in the future if needed.

The reason for the specific object structure is to maintain compatibility with Docker Image Labels, as well as maintain readability and prevent unneeded nesting within the `polykey agent status` command. 

### Additional context
Previous discussion on version metadata: https://github.com/MatrixAI/Polykey/issues/599

### Tasks

1. Rename non-conforming versionMetadata keys to be correct.

**Comment by CMCDragonkai** [comment]
What do you think of things like desktop, mobile? Will they have their own prefixes? Or will they not bother with that? Cause they will be presenting their own version anyway.
