### ISSUE TITLE
Add `--export` option to the `secrets env` command

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#145]
### Specification

We want to add export behaviour to the `secrets env` command. This will act similar to how `export key="value"` in linux. Essentially it will add the secrets selected with `-e vault:secretPath` to be added to the current environment.

This will need to work on all of the supported platforms. So it needs to work on windows too.

Unless I'm missing any nuance it should be as simple as adding the envs with `process.env[key]=value;`.

We need to decide if it will work along side the other functionality or become the main function when run. For example, if we run the command with `polykey secrets env -e vault1:secret1 --export some command` will it run `some command ` AND export to the current environment? OR just export? Same for the formatted outputs?

### Additional context

- Related #31 
- Related #129 
- Related #144 

### Tasks

- [ ] 1. Add the `--export` flag which will add the selected secrets to the current environment.
- [ ] 2. Make sure to support windows and all of the platforms.

**Comment by tegefaulkes** [comment]
I did a quick sanity check with

```
[brian@matrix-precision-3480-syzygy:~/workspace/Polykey-CLI]$ node -e "process.env.test='value'"

[brian@matrix-precision-3480-syzygy:~/workspace/Polykey-CLI]$ echo $test


[brian@matrix-precision-3480-syzygy:~/workspace/Polykey-CLI]$ 

```

So while we can set `process.env.key` to be whatever, it will only afffect the current process and any children. Wit will not be exported to the environment running the command. We'll need to find an alternative.

**Comment by CMCDragonkai** [comment]
I don't understand this sanity check? Why would we be using internal process.env? It would not be necessary.

27 Feb 2024 19:09:05 Brian Botha ***@***.***>:

**Comment by tegefaulkes** [comment]
Just checking if it was a viable way to do this but it doesn't work for our needs. I'll need to look into this more.

**Comment by tegefaulkes** [comment]
I recall from discussion that this is not actually a use case we want to support. If you want to export the env variables from the `secrets env` command you need to take the output from the command and do one of the provided terminal methods for doing this. The `secrets env` command shouldn't do it for you.

Closing as not planned.

**Comment by CMCDragonkai** [comment]
This is impossible to do.
