### ISSUE TITLE
`secrets edit` command race condtion

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#149]
### Specification

The `secrets edit` command writes the secret's contents to a temp file and opens an editor. The problem is this will be the same file across all concurrent calls of `secrets edit` resulting in clobbering.

```ts
const tmpDir = `${os.tmpdir}/pksecret`;
await this.fs.promises.mkdir(tmpDir);
const tmpFile = `${tmpDir}/pkSecretFile`;
await this.fs.promises.writeFile(tmpFile, secretContent);
execSync(`$EDITOR \"${tmpFile}\"`, { stdio: 'inherit' });
```

To fix this we'll need to make a tmpdir similar to how our tests work.

```ts
    dataDir = await fs.promises.mkdtemp(
      path.join(os.tmpdir(), 'polykey-test-'),
    );
```

### Additional context

- Related: #40 

### Tasks

1. Use a generated temp directory when creating the tempfile.
2. Add a test to check for concurrent usage and clobbering.

**Comment by CryptoTotalWar** [comment]
There's also an issue with secrets edit command that i think might be specific to MAC where it says that the editor doesn't have the required permissions to perform a secrets edit command and that permissions need to be configured at the admin level to do so. something like that. Let me know if you need me to provide more context and screenshots for this @tegefaulkes

**Comment by CMCDragonkai** [comment]
Yes create a new bug issue for that in Polykey-CLI, because Macs sometimes have specific permission issues. In this case, we are trying to create a temporary file and edit it. But wait until this is released. @tegefaulkes is this in the current release or next one?

**Comment by tegefaulkes** [comment]
@pablo.padillo You should test this again. If there is till an issue then make a bug issue for it.
