### ISSUE TITLE
Testnet Failure

### ISSUE THREAD

**Issue by amydevs** [MatrixAI/Polykey-CLI#153]
### Describe the bug

Started happening after 12:52 AEST Mar 7, 2024 on testnet seednodes. The error is too long to paste here, check https://ap-southeast-2.console.aws.amazon.com/ecs/v2/clusters/polykey-testnet/services/polykey-testnet-ap-southeast-2-v8k5smi8a5o7j4mhdka50q679op9lctdcepgkuslrhumc0ur793og/logs?region=ap-southeast-2

### To Reproduce

1. ...
2. ...
3. ...

**Comment by CMCDragonkai** [comment]
Not the right place for this issue. This is more of a PKNS problem.
