### ISSUE TITLE
Request: Allow For Publicly Accessible Vaults 

### ISSUE THREAD

**Issue by CryptoTotalWar** [MatrixAI/Polykey-CLI#161]
### Is your feature request related to a problem? Please describe.

For demonstration purposes, it would be advantageous to have vaults that anyone can clone without the need of another human. Currently, in order to showcase the capability of sharing secrets across the PK network requires 2 humans to tango. For the demo, usually developers will test this on their own, so having a publicly accessible vault demo purposes where they can clone that vault and get the secret to complete the demonstration, would be effective in showcasing the capabilities of the Pk network.

### Describe the solution you'd like

@tegefaulkes  can you take a stab at this?

### Describe alternatives you've considered

Will leave this open for feedback

### Additional context
@tegefaulkes please add here or in the comments thread

**Comment by tegefaulkes** [comment]
Hello!

**Comment by CMCDragonkai** [comment]
@CryptoTotalWar this would actually be quite complex to solve (would take months). Because it means providing a vault to be clonable from just `git` without PK at all. I don't think it would be clear to the end-user what this entails. In fact it was a bit unclear even from the description.

I imagine that initial tutorials may instead simply show the ability to share secrets between 2 PK agents that the user both owns. I'd argue that would be more important.

**Comment by CryptoTotalWar** [comment]
As things currently stand, the only way to showcase the sharing of secrets between two PK agents is either:
A) The user has to be active with another user to go through the discover, trust, share, clone, and get process.
B) The user needs to do this with two terminals for two PK agents they control, but this method won't create the impression we want, which is that the secrets are being shared through a decentralized encrypted network from one encrypted vault on one machine to another encrypted vault on another machine.

Option C was to create a PK Node (managed by Matrix.AI) where:
A) It is discoverable (maybe it requires following the Matrix AI GitHub repo).
B) The vault is PUBLIC and contains a secret file that anyone can pull from.
C) The PK node would trust everyone by default and grant pull access to its vault.

This sort of sandbox configuration is what we would want to enable to provide a straightforward Demonstration Tutorial Guide for users to test the full capabilities of Polykey with just the initial node they created and without needing to be actively live with another developer, simplifying the demo process.

**Comment by CryptoTotalWar** [comment]
@tegefaulkes , you had mentioned that this use case could be easily implemented. Would appreciate if you could provide further context of your initial assessment so that we may scope this out. As it stands currently, Roger's assessment is that this is not currently feasible, and I want to make sure that the way you were thinking this could be implemented is communicated properly.

**Comment by CryptoTotalWar** [comment]
From my standpoint, if this is not an easy fix and cannot be implemented and tested without bugs within the next 1-2 weeks, then it is not worth pursuing. In that case, I will figure out the demo process with the resources we currently have available.

**Comment by CryptoTotalWar** [comment]
Comments from @CMCDragonkai 

Because that's not possible. That would be a last mile integration. However, that wouldn't be quite relevant to the use cases that we have for last mile integration. The git sync is intended for vault sharing; that's specifically the highway of authority. However, that feature you are talking about can be done. However, due to how PK is being used, I'm not sure that would be a good idea. These are secrets in the vaults - it would not make sense to be "public." There must be an authenticated action to do the last mile push/pull. But this is a very different thing from the git sync that is being used in vault sharing. We need to spend some time talking about this. I have not been able to explain to you how PK actually works in every layer.

**Comment by CryptoTotalWar** [comment]
It was pointed out yesterday by Roger that:
A) This ticket is more appropriate for the Polykey repo instead of the polykey CLI repo so we should close this ticket. 
B) Realized that this feature request is not effective if just for demo purposes... instead we should focus on last-mile integrations to showcase on the polykey-docs.

**Comment by CryptoTotalWar** [comment]
Wont do

**Comment by tegefaulkes** [comment]
Just to add context.
 
What we discussed was having a publicly well know node in the tutorial that people could interact with without setting up a friend's node or a 2nd personal on. Just for demonstration purposes. We could have this node linked to the matrixai bot identity to show case discovery and have a vault on it that anyone could clone.

- The well know node and Identity can be used to demonstrate discovery with minimal set up
- A publicly accessible vault will allow people to practice cloning with minimal set up.

So as for how the feature will work. We just need to allow the ability to set a permission in the ACL to allow cloning and pulling of a vault by anyone. This functionality could be expanded to groups and resemble the user-group-everyone permissions of a file system but that will be a little excessive at this stage.
