### ISSUE TITLE
Support spaces in secret paths

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#199]
### Specification

Attempting `$ ~/Projects/Polykey-CLI/dist/polykey.js secrets create ./A\ B.md 'rippling:/A B.md'` results in the following error `error: command-argument value 'rippling:/A B.md' is invalid for argument 'secretPath'. rippling:/A B.md is not of the format <vaultName>:<directoryPath>`.

We should be able to handle file paths with spaces within them.

### Tasks

1. Support spaces within secret paths.
2. Added tests testing this functionality.

**Comment by CMCDragonkai** [comment]
I think we should support all allowed characters in Unix paths. Or the least common characters between Unix and Windows (windows have some restrictions). Not just spaces. A fast check test is needed.

**Comment by tegefaulkes** [comment]
I'm re-opening this. We want to explore using a Constraint parser for parsing the vaults secret path. This should also allow for escaping certain characters we'd otherwise disallow such as '='`. For example, `vault:this/secret\=name\==value` should be valid. `vault:this/secret\=name==value` would be invalid for having two un-escaped `=` and `vault:this/secret\=name\==value=` for having an invalid `=` in the value section.

That said, for the usage of `secret env` command, an `=` inside the secret name would be invalid since it would be an invalid environment variable name. Directory paths should be able to include `=` however.

Right now I'm pegging this expansion to the logic as a low priority. It's a lot of extra work just to allow `=` in the secret directory names.

On top of this, I think the error for failing to parse the vault secret path could be clearer and conditional. For example, if it failed to parse due to an invalid character, the exact reason needs to be defined.

**Comment by CMCDragonkai** [comment]
I think you should open up a new issue. The code of supporting spaces is done.

**Comment by tegefaulkes** [comment]
Closing this out. New issue at https://github.com/MatrixAI/Polykey-CLI/issues/223.
