### ISSUE TITLE
Format list of dictionaries with newlines between groups

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#200]
### Specification

Right now when we format the output for a command that list a bunch of entries. We end up with a very condensed list that is hard to read through. 

```
thing_one A
thing_two B
thing_one C
thing_two D
```
We want to modify all commands that are formatted like this to include a newline between entries.

```
thing_one A
thing_two B

thing_one C
thing_two D
```

### Additional context

Related: https://github.com/MatrixAI/Polykey-CLI/pull/178#issuecomment-2141117565

### Tasks

1. Format list of dictionary outputs to include a new line between entries.

**Comment by CMCDragonkai** [comment]
Technically this applies to all units of information. Lines have end of line. Dicts should have end of line (separate from key value end of line) and tables too... Etc. if we do this we naturally have a line separation.

Only thing is to trim the last newline of the output. But on streaming outputs you don't know if it's the last one. Or do you...? Either way one can specially handle the first one and do pre-output newline, or specially handle the last one.
