### ISSUE TITLE
Dual Stack Seednodes

### ISSUE THREAD

**Issue by amydevs** [MatrixAI/Polykey-CLI#213]
### Specification

Currently, the seednodes on `testnet.polykey.com` and `mainnet.polykey.com` only support IPv4. To implement IPv6 support, we will need to enable IPv6 on the seednodes by setting the `PK_AGENT_HOST` to `::`.

However having done this, I am coming up with this error when starting a PK node locally with `agent start --fresh -ah ::0` (binding to wildcard ipv6 interfaces).

```
WARN:polykey.PolykeyAgent.task v0pjjncdon1o01a9dvh67uog1gk:Failed - Reason: ErrorNodeManagerSyncNodeGraphFailed: Failed to establish any connections with the following errors '[ErrorNodeConnectionTimeout,ErrorNodeConnectionTimeout]'
```

When trying to ping the seednode with my local IPv6-only node, no response is gathered.

I have verified a Node connection can be established locally via only IPv6, having:

1. Started 2 PK agents using `agent start --fresh -ah ::0`
2. Use `nodes ping` to successfully ping one local node from another via MDNS discovery.

This confirms that IPv6 connectivity does in fact work. But there is some problem is specifying IPv6 seednodes.

### Additional context

Although none of this issue involves holepunching, it is worth revisiting this issue for context:

- https://github.com/MatrixAI/Polykey/issues/669

### Tasks

1. Change `PK_AGENT_HOST` to `::`
2. Debug IPv6 seednode issues

**Comment by amydevs** [comment]
upon further inspection, the connection attempts fail with

![image](https://github.com/MatrixAI/Polykey-CLI/assets/50583248/5b744f33-953d-4f7e-9223-f28e395bab91)

**Comment by amydevs** [comment]
upon even further inspection, it seems to be that `networkUtils.resolveHostnames` in PK does not resolve ipv6 hostnames
![image](https://github.com/MatrixAI/Polykey-CLI/assets/50583248/df27fea6-bb79-46b7-b698-0bc16fe99e8f)

**Comment by amydevs** [comment]
Having made the changes necessary to allow ipv6 hostname resolution, I'm now running into this error, where by the node will crash:

![image](https://github.com/MatrixAI/Polykey-CLI/assets/50583248/930039a3-4fc5-40b7-b7e3-4446f882c39f)

**Comment by amydevs** [comment]
reminder that this is with a non-dual-stack node that is only bound to ipv6

**Comment by amydevs** [comment]
with a dual stack `::` bound node, this works fine:

![image](https://github.com/MatrixAI/Polykey-CLI/assets/50583248/4be8c8c9-0172-4786-a9ba-4151b3300716)

**Comment by amydevs** [comment]
interestingly enough, the error + crash does not occur when an the node attempts to connect to ipv6 addresses on a non-dual-stack node only bound to ipv4. This could mean that we are possibly not correctly filtering out dual-stack ipv4-mapped-ipv6 addresses somewhere for nodes that are on an ipv6 socket, but cannot send to those addresses.

**Comment by amydevs** [comment]
okay, issue comes from some call to QuicSocket.send:

![image](https://github.com/MatrixAI/Polykey-CLI/assets/50583248/17c0945e-b0be-4dae-b0dc-b4587e0b6ff4)

there is an unhandled promise rejection somewhere, I'm willing to bet it's in js-rpc

**Comment by tegefaulkes** [comment]
That *should* be thrown by either the `QUICConnection` you're trying to start or the `QUICStream` if it only happened when triggered by an event in the stream.

It's very possible it could be leaking out of `js-quic` when starting the connection. So I'd sanity check that first, or at least, A/B test between quic and rpc domains.

**Comment by amydevs** [comment]
i found the issue, it's not out of RPC.

![image](https://github.com/MatrixAI/Polykey-CLI/assets/50583248/5fa2fdfc-e22e-4491-9ed7-891aa60c1d25)

`try finally` does not catch errors, so i was a bit confused here. If an error is thrown in a `try finally`, the error instead is thrown after `finally` block is ran. As soon as i added a no-op catch block, crashes no longer occured, and i ended up being able to ping the seednode via ipv6.

![image](https://github.com/MatrixAI/Polykey-CLI/assets/50583248/fac9baa4-c70a-4061-933a-4ee478ce43f6)

Callers of `NodeConnectionManager.holePunch` never catch the error, hence resulting in unhandled error rejections. I assume, that the intention here is that errors from `holePunch` should never be thrown, considering that we do not care about the reason that the holePunch fails, but only when the holepunch is initiated and when it has stopped.

**Comment by tegefaulkes** [comment]
Yeah, we usually don't care why the hole punch failed. We take the hole punch promise and push it into a map so we keep track of it. Then when shutting down we make sure they all complete or are cancelled.

That said, there's an annoying feature of promises. If you create one and don't await it or chain it in a way that handles the rejection *before* you yield to the event loop. If it rejects in that time it will be thrown as an unhandled rejection. Despite the fact that it would be handled later down the line in this case.

We've run into this problem with the task promises in the `TaskManager`. If you create a promise that can throw, and expect that it should be handled later. Then you need to hook a noop operation onto the `.catch` so node doesn't think it's unhandled. So we need to add a `void holePunchAttempt.catch(() => {});` to prevent this error before it can be handled later down the line.

**Comment by amydevs** [comment]
the only time where `holePunch` could throw is on the `.send` call. I've added a no-op catch to it, considering that outside of the function context, callers do not expect `holePunch` to ever throw, but to just simply resolve when it is timed out. This has been done.
