### ISSUE TITLE
Implement `secrets ls` command

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#245]
### Specification

The `secrets ls` command will list the contents of a directory.

There are 3 main features to support here.
1. List directory normally
2. List in list format `-l`
3. Include hidden files with `-a`
4. Paths can support wildcards and globing.
5. Multiple paths can be specified.
6. `stdin` is ignored

```
Polykey/tmp/asd on  staging [?] 
❯ ls
asdasd  best  dir1  dir2  one  test  two

Polykey/tmp/asd on  staging [?] 
❯ ls -l
total 32
-rw-r--r-- 1 brian operators  8 Jul 11 11:18 asdasd
-rw-r--r-- 1 brian operators 15 Jul 11 11:18 best
drwxr-xr-x 2 brian operators  2 Jul 11 11:19 dir1
drwxr-xr-x 2 brian operators  2 Jul 11 11:19 dir2
-rw-r--r-- 1 brian operators  0 Jul 11 11:18 one
-rw-r--r-- 1 brian operators  5 Jul 11 11:18 test
-rw-r--r-- 1 brian operators  0 Jul 11 11:18 two

Polykey/tmp/asd on  staging [?] 
❯ ls -a
.  ..  asdasd  best  dir1  dir2  .hidden  one  test  two

Polykey/tmp/asd on  staging [?] 
❯ ls *est
best  test

Polykey/tmp/asd on  staging [?] 
❯ ls **/*     
asdasd  best  dir1/a  dir2/b  dir2/c  one  test  two

dir1:
a

dir2:
b  c

Polykey/tmp/asd on  staging [?] 
❯ ls -l **/*
-rw-r--r-- 1 brian operators  8 Jul 11 11:18 asdasd
-rw-r--r-- 1 brian operators 15 Jul 11 11:18 best
-rw-r--r-- 1 brian operators  0 Jul 11 11:42 dir1/a
-rw-r--r-- 1 brian operators  0 Jul 11 11:43 dir2/b
-rw-r--r-- 1 brian operators  0 Jul 11 11:43 dir2/c
-rw-r--r-- 1 brian operators  0 Jul 11 11:18 one
-rw-r--r-- 1 brian operators  5 Jul 11 11:18 test
-rw-r--r-- 1 brian operators  0 Jul 11 11:18 two

dir1:
total 1
-rw-r--r-- 1 brian operators 0 Jul 11 11:42 a

dir2:
total 1
-rw-r--r-- 1 brian operators 0 Jul 11 11:43 b
-rw-r--r-- 1 brian operators 0 Jul 11 11:43 c

❯ ls **/*
asdasd  best  dir1/a  dir2/b  dir2/c  one  test  two

dir1:
a

dir2:
b  c

```

### Additional context

Related #32 

### Tasks

1. Implement `secrets ls` command
2. Support the default format.
3. Support the list `-l` format
4. Files and directory's that start with `.` should be hidden unless `-a` is used.
5. Support wild cards and globing.
7. Support specifying multiple paths.
8. Seamlessly support using normal and secret paths.

**Comment by CMCDragonkai** [comment]
Although the EFS (based on VFS) fully supports file permissions, it sort of meaningless in the context of Polykey. Furthermore the user is always root.

So in a way I'm not sure if we should fully replicate the the whole unix permission and user output that `ls` normally does as it assumes am multi-user unix system.

That being said, maintaining similar textual format makes it easier to pipe into other commands. One might just default to `rwxrwxrwx`... etc.

**Comment by aryanjassal** [comment]
The command now lists contents based on the directory name instead of listing all the files by default. The remaining tasks will be tracked by https://github.com/MatrixAI/Polykey-CLI/issues/278#issue-2515291286 ([ENG-406](https://linear.app/matrix-ai/issue/ENG-406/continuation-of-implementing-secrets-ls-command)).

**Comment by CMCDragonkai** [comment]
What do you mean based on directory name? It should also list all files right?

**Comment by aryanjassal** [comment]
If you pass in a directory name, then it will list all contents of that directory, instead of listing all the files that exist in the vault, which was the behaviour of the old `polykey secrets list`

**Comment by CMCDragonkai** [comment]
Are you also removing the old `list` command too? I don't want those vestigial commands left around.

**Comment by aryanjassal** [comment]
Yes, the old `list` command has been removed.

**Comment by CMCDragonkai** [comment]
Great!
