### ISSUE TITLE
Implement `secrets rm` command

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#247]
### Specification

The `secrets rm` command will remove one or more files specified by paths.

1. Will remove the file at the specified path.
2. Multiple paths can be specified.
3. Supports wildcard and globing.
4. Supports a `-r` recursive option for deleting directories with contents.
5. Supports normal and secret paths.

### Additional context

Related #32

### Tasks

1. Implement `secret rm` command.
2. Supports multiple specified paths.
3. supports wildcard and globing
4. supports a `-r` option to recursively delete directories and their contents.

**Comment by tegefaulkes** [comment]
@aryanj this one comes after the `cat` command. Ignore tasks 3 and 4 for now. Should be simple to implement since it doesn't require and content streaming.

**Comment by aryanjassal** [comment]
> @aryanj this one comes after the `cat` command. Ignore tasks 3 and 4 for now. Should be simple to implement since it doesn't require and content streaming.

The `secrets cat` command relies on the implementation of streaming file contents via the `VaultsSecretsGet` handler. It *can* work without it, but it would need to be changed anyways once that has been implemented. As we still need to put a bit more thought into that, I will be working on this command.

**Comment by aryanjassal** [comment]
> I don't think we even can implement the -f option, as that option forcefully removes unwritable files, but the vaults don't have any concept of actual file perms, so it will be redundant.

Following this, I will remove `-f` from spec.
