### ISSUE TITLE
Bundling and fixing pkg

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#25]
### Specification

This is an epic that tracks the progress of getting the CLI fully working.

I'll add the relevant issues to this epic after reviewing them.

### Additional context

* Commentary https://github.com/MatrixAI/Polykey-CLI/pull/4#issuecomment-1748016768
* Related: #23 
* Related: https://github.com/vercel/pkg-fetch/issues/285

### Tasks

1. Use a bundler to combine the source into a single js file.
2. Check that all artefacts that we need are included and any spurious stuff is left out.
3. Check that the single js file runs as expected using node.
4. package the single js file with `pkg` and ensure it runs properly.

**Comment by tegefaulkes** [comment]
This really consists of two main parts. 
1. Selecting and applying a bundler and getting that working.
2. getting pkg to work with the bundled code and node20.
3. 

What bundler are we going to go with?

**Comment by CMCDragonkai** [comment]
#23 and https://github.com/MatrixAI/TypeScript-Demo-Lib/issues/32

- esbuild

**Comment by CMCDragonkai** [comment]
https://github.com/vercel/pkg-fetch/issues/285#issuecomment-1748056724
