### ISSUE TITLE
Discrepancy in claim, discover and trust commands in CLI

### ISSUE THREAD

**Issue by addievo** [MatrixAI/Polykey-CLI#28]
### Specification

Currently the claim command in Polykey-CLI uses the following syntax 

```typescript
npm run polykey -- identities claim github.com GITHUBUSERNAME
```

Whereas the discover and trust commands use 

```typescript
npm run polykey -- identities discover github.com:ANOTHERGITHUBUSERNAME
npm run polykey -- identities trust github.com:ANOTHERGITHUBUSERNAME
``` 

The claim command is out of sync of trust and discover, as they both utilize a COLON to separate provider and identity, whereas the claim command uses a space, this discrepancy is a bug.

### Tasks

1. `src/identities/CommandClaim.ts` to alter the input args to be in-line with trust and discover.
2. ...
3. ...

After this change, all the identity related functions of polykey would be syntactically identical.

**Comment by CMCDragonkai** [comment]
This is not a bug.
