### ISSUE TITLE
The `pk secrets env` command for meeting Development Environment Usecase

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-CLI#31]
### Specification

1. The `pk secrets env` command should operate similar to the unix `env` command
2. We can use `pk secrets env` to do double duty: inject environment variables into a new subcommand, or allow sourcing of environment variables into an existing subshell
3. The task for the development environment usecase is specified in https://github.com/MatrixAI/Polykey-Desktop/issues/77
4. The `pk secrets env someprogram arg1 arg2` should do a proper process replacement when possible

### Additional context

* https://github.com/MatrixAI/js-polykey/issues/55#issuecomment-658668800 - old comment about the env interface and the "chording" idea

Copied excerpt:

> Now when we want to start development on the project, we have 2 options:
> 
> 1. Open up a shell with Polykey sourcing the environment variables
> 2. Use Polykey to inject environment variables into a sub-shell
> 
> Either result is the same, because you'll be running a shell with environment variables set so that your test runs of your software can inherit this environment configuration. Let's demonstrate both.
> 
> In the first case, we will reuse the `source` command and ask `pk` to constuct the equivalent of the `.env` file but entirely in-memory and only for this specific usage. We must also use process substitution `<(...)` so that the `pk` command output can be redirected into a temporary file descriptor that is read by the `source` command.
> 
> ```sh
> # one secret
> source <(pk secrets env my-software-project:AWS_ACCESS_KEY_ID)
> 
> # multiple secrets
> source <(pk secrets env my-software-project:AWS_ACCESS_KEY_ID my-software-project:GOOGLE_MAPS_API_KEY)
> 
> # globbing style (you can use globstar as well, this will only export immediate files)
> source <(pk secrets env my-software-project:*)
> 
> # use the -e flag to export all variables
> source <(pk secrets env -e my-software-project:*)
> # use the -- to separate so you can export just one out of many
> source <(pk secrets env -- my-software-project:AWS_ACCESS_KEY_ID -e my-software-project:GOOGLE_MAPS_API_KEY)
> source <(pk secrets env -e -- my-software-project:AWS_ACCESS_KEY_ID my-software-project:GOOGLE_MAPS_API_KEY)
> ```
> 
> Now your shell has the relevant environment variables set by Polykey, and they will exist for as long as this current shell is alive.
> 
> In the second case, we ill use `pk secrets env` command to run a subshell, it can run any subprogram, but in the context of a development environment, you usually want a shell.
> 
> ```sh
> # one secret
> pk secrets env my-software-project:AWS_ACCESS_KEY_ID bash
> 
> # multiple secrets
> pk secrets env my-software-project:AWS_ACCESS_KEY_ID my-software-project:GOOGLE_MAPS_API_KEY bash
> 
> # globbing style
> pk secrets env my-software-project:* bash
> 
> # the -e flag has no effect when using it this way
> # this is because the subprogram determines whether to export variable or not
> # it usually exports the variable
> pk secrets env -e my-software-project:* bash
> ```
> 
> Now you have a subshell that has the environment variables configured, it will also automatically export it to child programs. When you have finished your development, you can just `exit` the shell, and the environment variables are gone!

### Tasks

1. Ensure that `pk secrets env` can be used to inject environment variables and run a subprocess
2. Ensure that `pk secrets env` can be used to source environment variables and output something that can be used as a file to be sourced by a shell
3. Deal with the fact that nodejs doesn't have an exec that can replace the current node process: https://github.com/nodejs/node/issues/21664
   * You can deal with this the way babel deals with it

> * Babel [attempts to use `kexec`](https://github.com/babel/babel/blob/master/packages/babel-node/src/babel-node.js#L87-L88) where available, which [is a POSIX-only module that replaces the process literally](https://www.npmjs.com/package/kexec). Absent that, it falls back to [its own implementation](https://github.com/babel/babel/blob/master/packages/babel-node/src/babel-node.js#L90-L109) that works like the other two examples.

**Comment by CMCDragonkai** [comment]
New update https://github.com/StorytellerCZ/node-kexec.

I think we should be able to integrate this into our own library `js-exec`.

We can incorporate windows support with this understanding:

> The closest equivalent to the `exec` system call in Linux, which replaces the current process image with a new one, in Windows is the `CreateProcess` API. Unlike `exec`, `CreateProcess` starts a new process rather than replacing the current one. However, you can work around this by terminating the original process after `CreateProcess` successfully launches the new one.
>
> It's worth noting that the behavior of `exec` and `CreateProcess` are fundamentally different. In the Linux/Unix model, using `exec` in a process replaces the current process image with a new one but keeps the same process ID. Any file descriptors that are marked as close-on-exec are closed, otherwise they remain open. This allows for process chaining and replacement without process tree disruption.
>
> In contrast, Windows' `CreateProcess` spawns a new process with a different process ID. It's more like a combination of `fork` and `exec` in Linux, but without the inherent cloning of the parent process. File handles are not automatically inherited unless specified. Thus, it creates a new entity in the process tree rather than replacing an existing one.
>
> So, although `CreateProcess` is the closest native API Windows has to offer, it doesn't provide an exact one-to-one match with the `exec` system call in Linux.

**Comment by tegefaulkes** [comment]
On request I'm adding this issue to the #40 epic

**Comment by tegefaulkes** [comment]
Some notes about the scope.

1. There are two styles this command would work. First is the process replacement style where the process of the env command is replaced with the command it's invoking. The second style will just be a normal exec of invoked command. The second style will only be used if the replacement isn't supported. We'll be looking at `https://github.com/StorytellerCZ/node-kexec` for this.
2. The main goal of the env command is to run the invoked command with environment variables taken from vaults.
3. We'll need to work out how these environment variables will be structured within the vaults and secrets. I can think of two formats, the first being a `Record<string, string>` JSON object encoding the env key and value. Alternatively we can store the key:value mapping with the secrets where the secret name is the key and the contents the value. This will have to be worked out with consideration of how vaults schema will work. I'm thinking keeping to the structure of vaults and secrets without structure on top of that may work best here?
4. We need a way to pick and choose what env variables we want to use. Also have some way of mixing them together arbitrarily by listing what envs we want from what vaults and possibly using globstar patterns.
5. We can have an alternative usage where the env command spits out the environment variables without running a command. So It can be composed in other ways. 

So there are a few components to this that need to be addressed and specced out.
1. We need some way to list out the env variables we want to use from vaults using the cording method. We'll need the ability to reference multiple env names across multiple vaults and possibly with globbing/regex to avoid listing out every variable. Commander may have a way to specify a flag multiple times so we end up with an array of flag parameters. Or its all passed in as one flag and we have a complex parser to handle it.
2. We need to look into schemas or create a stopgap schema for storing env variables in vaults. Either way we need to spec out how to structure the envs in the vaults.
3. We need a way to output the env variables in a structure that can be composed with other commands or in scripts.
4. We need a way to exec a command we provide with the envs we want. On linux based platforms we want to replace the env command process with the invoked command. if that is not supported then we fall back to exec.

**Comment by tegefaulkes** [comment]
I'll start with scaffolding the command.

**Comment by CMCDragonkai** [comment]
I think put a simple C++ or rust code into it to expose the proper exec. For windows it's not possible so we won't bother. The rust is likely far simpler than the C++ scaffold with the bonus of being similar to js-quic and subsequently deno.

**Comment by CMCDragonkai** [comment]
Note that @amydevs has experience with the setup of a partial native module.

**Comment by tegefaulkes** [comment]
Will we need to do any native code if we use https://github.com/StorytellerCZ/node-kexec ?

**Comment by tegefaulkes** [comment]
As for specifying the enviroment variable we want with the command. Commander provides a varadic option. https://github.com/tj/commander.js?tab=readme-ov-file#variadic-option This will allow us some freedom in specifying the enviroment variables that we will get as an array that can be parsed.

**Comment by CMCDragonkai** [comment]
I don't want to use other people's native code. It will be flexible. This is a simple enough function for our own js-exec.

**Comment by amydevs** [comment]
I think cpp would be better to use than Rust here. If we were to use Rust, we would need to bring in native bindings to apis and writing unsafe code anyways. Also memory safety shouldn't be hard with the limited complexity of it anyways.

**Comment by tegefaulkes** [comment]
I'd lean towards not deviating from how we do native bindings in other repos. If only to reduce entropy by having everything stick to a standard way of handling it.

**Comment by CMCDragonkai** [comment]
> I think cpp would be better to use than Rust here. If we were to use Rust, we would need to bring in native bindings to apis and writing unsafe code anyways. Also memory safety shouldn't be hard with the limited complexity of it anyways.

We should be migrating to rust - for demo compatiblity. Plus the js-quic is much more modern package distribution compared to js-db. Everything new native should be rust.

**Comment by CMCDragonkai** [comment]
@tegefaulkes is there anything in the original issue spec that you're changing? As per this comment https://github.com/MatrixAI/Polykey-CLI/issues/31#issuecomment-1938121485

**Comment by tegefaulkes** [comment]
It's mostly the same except for the following.

1. I'm not implementing regex or globbing when selecting secrets. But mixing matching specific secrets and directories of secrets is allowed.
2. I'm adding extra functionality to generate `.env` style output or `a="secret" b="secret"` style output.

**Comment by CMCDragonkai** [comment]
Is there a need for PR for PK too? Link them here too.

**Comment by CMCDragonkai** [comment]
It's important for us to be able to source the secrets too so we can use it inside the shell hook @brynblack.

**Comment by CMCDragonkai** [comment]
The `js-exec` repo on gitlab is configured - however the CI isn't correct, it needs to be setup to not build for Windows. Make sure to refer to the `js-mdns` that @amydevs setup.

**Comment by CMCDragonkai** [comment]
> We need to look into schemas or create a stopgap schema for storing env variables in vaults. Either way we need to spec out how to structure the envs in the vaults.

I don't think that's necessary yet, simply referring to the file path is enough.

> We need a way to output the env variables in a structure that can be composed with other commands or in scripts.

Yea that's just `source <(pk secrets env my-software-project:AWS_ACCESS_KEY_ID)`.

Without the command, it can just print out a consumable shell settings. And I believe `.env.example` is the format.

That will set it to the current shell, but not necessarily export them.

To do that:

```
set -o allexport
source <(...)
set +0 allexport
```

We do this already in our shellhook.

Note that on Windows, the syntax is not compatible. So we would have to have a switch when outputting to powershell format: https://stackoverflow.com/a/51247258.

```
$variable = "abc"
$env:variable = "abc"
```

That's a bit more complicated because the `$env` has to be used to export them to the environment... And this would require a flag like `--windows` for this command or something. Or I guess `powershell`. Like `--powershell` to switch it around because CMD is actually different.

**Comment by CMCDragonkai** [comment]
Someone came up with a PS script that can interpret unix style syntax: https://stackoverflow.com/a/74839464.

That's another way, which is to simply provide that execution and embed the above content like a heredoc.

But still doesn't solve the ability to auto-export. It seems weird to have to always set the `--export` option, but that could be another flag that even enables `export X=Y`.
