### ISSUE TITLE
Rename `vaults list` command to `vaults ls`

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#310]
### Specification

@CMCDragonkai mentioned that since the `secrets list` has become `secrets ls` now, we should rename the vaults list command the same.

So the `vaults list` command should be renamed to `vaults ls` with `list` as an alias.

### Tasks

1. Rename `Vaults list` to `vaults ls`.
2. Include `list` as a command alias.
3. Update tests to reflect this change.

**Comment by CMCDragonkai** [comment]
In general, anything that is `list` could be `ls`.

**Comment by CMCDragonkai** [comment]
You want to have `list|ls` available for these sorts of commands.

**Comment by CMCDragonkai** [comment]
Short versions of all commands should exist like `remove|rm` if it makes sense...

**Comment by aryanjassal** [comment]
> Short versions of all commands should exist like `remove|rm` if it makes sense...

Oh. I'll make a new issue to convert all commands, vault or otherwise, to have short/long versions where applicable.

**Comment by aryanjassal** [comment]
<b>[Polykey-CLI#323](https://github.com/MatrixAI/Polykey-CLI/issues/323)</b>
