### ISSUE TITLE
`secrets edit` should maintain the websocket as long as the editor session is alive

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-CLI#315]
### Specification

When using `secrets edit`, it will timeout if the editor session isn't finished fast enough. I opened up the `secrets edit` and waited for a while, after trying to save, it failed:

```
cmcdragonkai ➜ matrix-framework-13-ryzen-7040  ➜ ~/Projects/Polykey-CLI
 $ ./dist/polykey.js secrets ed nix:/nix.conf
ERROR:polykey.PolykeyClient.WebSocketClient:ErrorWebSocketConnectionKeepAliveTimeOut: WebSocket Connection reached keep-alive timeout - 
ERROR:polykey.PolykeyClient.WebSocketClient.WebSocketConnection 0:ErrorWebSocketConnectionKeepAliveTimeOut: WebSocket Connection reached keep-alive timeout - 
ErrorWebSocketConnectionNotRunning
```

We need to make the websocket connection alive for as long as the editor session is alive, it shouldn't fail.

That being said it's also important not to start a vault commit transaction until the editor has in fact finished writing. We don't want this to block other secret operations. Concurrent testing needs to be checked too.

### Tasks

1. Use a stream life cycle to be maintained while the editor is there, it shouldn't expire on the keep alive timeout.
2. Test that secrets edit can work for a long running edit.
3. Test that while the editor is open it doesn't cause blocked concurrent secrets operations.

@tegefaulkes @aryanjassal

**Comment by CMCDragonkai** [comment]
I want to point out that this message looks weird too:

```
INFO:polykey.PolykeyAgent.ClientService.WebSocketServer.WebSocketConnection 0:ErrorWebSocketConnectionPeer: WebSocket Connection peer error - Peer closed with code 1000
```

This looks like a error. But it's actually a successful close. It's considered normal closure.

**Comment by aryanjassal** [comment]
I also encountered this issue. After a short discussion with Brian, our conclusion was that this is being caused due to the `execSync` block launching the editor. The `execSync` might be blocking everything else from running, which might include the websocket pings, and that might be causing this issue.

After <b>[Polykey-CLI#305](https://github.com/matrixai/polykey-cli/pull/305)</b> is completed, I can start work on this issue.

**Comment by aryanjassal** [comment]
After some quick investigation, I have realised that `execSync` does, in fact, block everything until the command is finished. To resolve this, an async `exec` is needed.

```ts
try {
  const stdout = await new Promise((resolve, reject) => {
    exec(command, (error, stdout, stderr) => {
      if (error) {
        reject(error);
      } else if (stderr) {
        reject(new Error(stderr));
      } else {
        resolve(stdout);
      }
    });
  });
} catch (e) {
  // Promise rejected. There was an error.
}
```
