### ISSUE TITLE
`nodes status` command should include connection and graph stats

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#36]
### Specification

We want to expand the `agent status` command to output some basic stats about the number of active connections and known nodes in the graph.

Suggestions about other stats are welcome.

### Additional context

* Related https://github.com/MatrixAI/Polykey/issues/551
* Related https://github.com/MatrixAI/Polykey/issues/551#issuecomment-1767816696

### Tasks

1. add basic stats about connections to the `agent status` command.
2. add basic stats about known nodes to the `agent status` command.

**Comment by addievo** [comment]
@tegefaulkes, please expand on what stats you want, rn I have added number of active connections, I tried getting info of all connected nodes but its too clinky in the format

**Comment by tegefaulkes** [comment]
You just want summary of stats for relevant domains. Stuff like.
1. Number of nodes in node graph
2. known gestalts,
3. size of own gestalt
4. size of the sigchain

Stuff like that. Roger mentioned 

```
Roger Qiu — Today at 8:50 AM
Just get it all
acitve connections
node graph
gestalt graph size
gestalt size
sigchain claims
its a useful
```
