### ISSUE TITLE
Fix and re-enable any disabled tests

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#37]
### Specification

There are some disabled tests in the CLI right now. There are two nodes ping tests but here may be others that need to be fixed.

The `nodes ping` tests were disabled after the fail to ping tests were throwing the wrong error. I think this needed to be fixed in `Polykey` but check the tests first.

Any other test that is disabled with `.skip` or `testIf(false)` need to be checked and re-enabled if needed.

### Additional context

* Related https://github.com/MatrixAI/Polykey/issues/551
* Related https://github.com/MatrixAI/Polykey/issues/551#issuecomment-1767816696

### Tasks

* [x] 1. Fix and re-enable the `nodes ping` tests.
* [x] 1. Find, fix and re-enable any other tests that are disabled.

**Comment by tegefaulkes** [comment]
As it stands, the following tests are disabled

1. tests/nodes/ping.test.ts - 2 tests
2. tests/agent/start.test.ts - 1  test
3. tests/integration/testnet/testnetConnection.test.ts - 2 tests
4. tests/nat/DMZ.test.ts
5. tests/nat/endpointDependentNat.test.ts
6. tests/nat/endpointIndependentNat.test.ts

**Comment by tegefaulkes** [comment]
I've made a start on this, but some of the tests require a fix to MatrixAI/js-rpc. I'll make a new issue there for tracking the problem.

**Comment by CMCDragonkai** [comment]
NAT related tests are hard to replicate and hard to maintain.

Consider we love NAT tests to the simulation infrastructure using Pulumi @amydevs.

Export the code and keep it in Polykey-Simulation on gitlab.
