### ISSUE TITLE
nodesConnections IP mapping issue

### ISSUE THREAD

**Issue by addievo** [MatrixAI/Polykey-CLI#47]
DRAFT

### Specification

`pk nodes connection` is is sometimes lising the IP as as a `ipv6` mapped `ipv4` address. This needs to be looked into.

### Tasks

1. ...
2. ...
3. ...

**Comment by CMCDragonkai** [comment]
@tegefaulkes can you look into this. And close this if this is solved?

**Comment by CMCDragonkai** [comment]
This is already done as per https://github.com/MatrixAI/Polykey/issues/614
