### ISSUE TITLE
CSV Import functionality/Secret imports

### ISSUE THREAD

**Issue by addievo** [MatrixAI/Polykey-CLI#51]
This is one of the issues which would make Polykey "cool" and easy to migrate for most users, who wish to store passwords. 
This is CRUCIAL to implement for early adopters. 

### Requirements of this design

1. Most password managers allow exporting secrets (logins) in form of CSV.
2. Polykey should allow importing of these secrets (passwords).
3. This is key as no one would manually import 100's of passwords/secrets.

### Specification

1. Get the design of exports from major competitors, Bitwarden, Lastpass, Google passwords (lol?), etc.
2. Convert to PK secrets.
3. Auto add secrets to a particular vault

**Comment by CMCDragonkai** [comment]
It's likely that the the CSV format of alot of these programs are not standardized, and so it's not possible to auto-import.

This would better suited to a separate third party program that acts as an importer script that is coded to that platform and then maps it to PK using the new CLI commands in #32.

At this point, not relevant to PK CLI.
