### ISSUE TITLE
Improper use of `retryAuthentication` with streaming calls

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#78]
### Specification

`retryAuthentication` is a utility that will prompt for a password if an RPC call failed with an authentication error. It's a bracketing pattern that wraps the action and catches the error. For most uses where the response is a promise this works fine.

However, for server and duplex streams, any errors are thrown through the stream. In this case the `retryAuthentication` will return the response stream without interacting with the error and completely fail to do it's job. Basically, if the `retryAuthentication` returns the response stream then it will fail to do it's job.

For any streaming calls we need to make sure that the stream is fully consumed within the the `retryAuthentication` callback or we need a version of `retryAuthentication` that works with streams.

I skimmed over the code and I think the only place where this would still be an issue is `commandRead.ts` but keep an eye out for other places.

### Additional context

* Related #40 

### Tasks

1. review any usage of streaming with `retryAuthentication`.
2. Fix any broken usage of this.

**Comment by CMCDragonkai** [comment]
You need this to work for any RPC calls. I'm not sure about consuming the entire stream. Wouldn't that just result in wasted cycles? Is that the only way?

**Comment by tegefaulkes** [comment]
No not the only way. We just can't return the stream directly unless we make a version of `retryAuthentication` that works with streams.

**Comment by CMCDragonkai** [comment]
Even on streams the first error will be some unauthenticated exception and so it should be easy to create one to deal with this.

**Comment by tegefaulkes** [comment]
I found one place where this was still a problem. That was `notifications read`. Since it's a small change I'm pushing the fix direct to staging.
