### ISSUE TITLE
Split Secrets and Vault Command Tests into Separate Files

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#80]
### Specification
- `tests/bin/secrets/secrets.test.ts` (every secrets bin command should have its own test file located in `tests/bin/secrets` and `secrets.test.ts` can be removed)
- `tests/bin/vaults/vaults.test.ts` (every vaults bin command should have its own test file located in `tests/bin/vaults` and `vaults.test.ts` can be removed)
- ~`tests/client/rpcVaults.test.ts` (every vaults client service handler should have its own test file located in `tests/client/service` and `rpcVaults.test.ts` can be removed)~
- ~`tests/agent/GRPCClientAgent.test.ts` (every vaults agent service handler should have its own test file located in `tests/agent/service` and all vaults-related tests can be removed from `GRPCClientAgent.test.ts`)~

### Additional context

* relates to https://github.com/MatrixAI/js-polykey/pull/266#issuecomment-1050504009
* Relates MatrixAI/Polykey#266 
* Relates MatrixAI/Polykey#311 

### Tasks

1. Expand out spec and tasklist

**Comment by CMCDragonkai** [comment]
This is moved into PK CLI because only 2 things in the spec are relevant now to the PK CLI since the bin was factored out.

Vaults tests is a separate problem.
