### ISSUE TITLE
Remove deployment triggering from CI job

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#90]
### Specification

I need to remove the part of the job `integration:deployment` that triggers the testnet seed nodes tasks restarting with the newly deployed image. But it depends on the new lambda handling that for us. Right now I don't think it's triggering properly so I'm leaving the CI job as is to be updated later.

### Additional context

* Related #71 

### Tasks

1. Verify the lambda is triggering the deployment properly.
2. Remove the part of the CI job `integration:deployment` that triggers the tasks restarting.
4. The wait-for-deployment.js needs to be parameterised to work with the testnet and mainnet.
5. The integration tests need to be parameterised to work with the testnet and mainnet.
6. The wait-for-deployment.js script needs to take into account the CLI version on top of the library version.
7. we need to add a wait-for-deployment ci job for the mainnet stage.
8. We need add integration tests ci job for the mainnet stage.

**Comment by tegefaulkes** [comment]
I need to confirm the status of the lambda triggering the update of the seed nodes from @amydevs.

I believe that @amydevs is also working on including the CLI version in the status information. With that included I'll need to update the `wait-for-deploy.js` script to use it.

**Comment by CMCDragonkai** [comment]
I believe that should be done already. Can you check?

**Comment by tegefaulkes** [comment]
There are actually a few parts needed to complete this so I'm going to be expanding this issue.

1. Remove the ECS service update from the CI job. This was the main point of this issue and is unchanged.
2. The `wait-for-deployment.js` needs to be parameterised to work with the testnet and mainnet.
3. The integration tests need to be parameterised to work with the testnet and mainnet.
4. The `wait-for-deployment.js` script needs to take into account the CLI version on top of the library version.
5. we need to add a `wait-for-deployment` ci job for the mainnet stage.
6. We need add integration tests ci job for the mainnet stage.
