### ISSUE TITLE
Specify `--network` with URL such as `testnet.polykey.com`

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#97]
### Specification

Currently the network option takes either `mainnet` or `testnet`, these are hard-coded into the config file and resolved to the URLs `mainnet.polykey.com` and `testnet.polykey.com` respectively. 

We should change this to use the `mainnet.polykey.com` or `testnet.polykey.com` directly. So when selecting the network option when starting polykey it's either specified with the option as `---network mainnet.polykey.com` with the default as `mainnet.poykey.com. The ENV variable will likewise be the same `PK_NETWORK=mainnet.polykey.com`.

This will slightly reduce the complexity while allowing any properly set up network URL to be used.

### Additional context
* Related: https://github.com/MatrixAI/Polykey-CLI/pull/94#discussion_r1454363391

### Tasks

1. Remove network names and information from the `Polykey` config.js.
2. Update the CLI option to take and parse hostnames.
3. Update the CLI option to default to `mainnet.polykey.com`.
4. Update any tests that depend on this change.
5. Update any CI jobs that depend on this change.

**Comment by tegefaulkes** [comment]
This is already done right? Didn't @amydevs fix this a while back?

**Comment by CMCDragonkai** [comment]
Can you verify?

**Comment by tegefaulkes** [comment]
Nope, not actually done yet. The CLI option still needs to be modified to take the URL rather than the network name.

**Comment by amydevs** [comment]
this should be the case already.

**Comment by amydevs** [comment]
I've made the change on staging, I now need to make the change in Orchestrator as well. Otherwise the deployment of seednodes will be set to the wrong hostname

**Comment by CMCDragonkai** [comment]
So CLI PR and Orchestrator PR then? Need to reopen.

**Comment by CMCDragonkai** [comment]
Oh is the Polykey-CLI done here then? https://github.com/MatrixAI/Polykey-CLI/pull/210/commits/35258268e9a80f00e745ab3db2ab61176c2e7ab7.

Orchestartor PR could be done separately - but should be kept track here.

**Comment by amydevs** [comment]
This has already been done in Orchestrator, I just pushed a commit because it was a 1 line change:

[https://github.com/MatrixAI/Orchestrator/commit/935bd07cbe447d30046638c5a8f931c39773c813](https://github.com/MatrixAI/Orchestrator/commit/935bd07cbe447d30046638c5a8f931c39773c813)
